### ISSUE TITLE
"Issues" theme sable

### ISSUE THREAD

**Issue by thatbritguy** [Hellowlol/HTPC-Manager#303]
Just a few random bugs I've noticed from an initial glance:
- On a mobile device the menu button doesn't work so you can't access anything.
- You need to add in files for the heavier theme variant as if the heavy option is enabled when someone selects sable the page doesn't load as it's looking for a theme file that doesn't exist.
- Login page - the login button is shorter than the input fields so looks odd.
- Buttons on the breadcrumb (e.g. settings pages) don't appear as buttons, just text as the button color is the same as the breadcrumb color.
- The refresh buttons on the dashboard modules are so minuscule that they're super hard to click with a mouse and almost impossible to hit on touch devices.
- Module headers on dash are same font size as the body text, as are titles in page header bar. Although the heading is larger on the Settings page but it's also way over to the left beyond the content margin - page header titles need to be level with the start of the navbar brand logo.
- Dropdown menus in page header are offset from the actual header so there is a gap between the menu and the bar.
- Dividers on page header drops are showing up weird and really thick (think it's because you left the black background on the dividers).
- Dropdown from nav-tabs within modules are also offset and have a gap between the tab and the actual dropdown.
- In Plex page header the Wake button icon and text are different to everything else (light grey so hard to see) and are also not aligned with the other buttons.
- Thumbnail item titles in Plex, Kodi, CouchPotato etc need to be either smaller or lighter as with certain titles it can push the final thumbnail beyond the content margin so it moves to next row and leaves a gap.
- Sonarr_view page - the settings button icon is way too small.
- Table heading text is so bold the letters are almost touching which makes it a little hard to read.

**Comment by bakman2** [comment]
Good debug thanks. I will look into all the issues.
For Plex - where is a "wake button" ? i don't see it ?

**Comment by Hellowlol** [comment]
You need to enter the mac :)

https://github.com/Hellowlol/HTPC-Manager/blob/master2/interfaces/default/html/plex.html#L24

**Comment by fma965** [comment]
![image](https://cloud.githubusercontent.com/assets/1707290/9107770/d97c2ee6-3c21-11e5-9924-a4386961fce9.png)
Is the menus and title background meant to look like this?

**Comment by fma965** [comment]
2015-08-06 10:03:37 webui.console.errors    ERROR   {'message': u'Uncaught Error: Syntax error, unrecognized expression: #nav-couchpotato (movies)', 'line': u'34', 'file': u'http://remote.cyanlabs.net/htpc/js/libs/jquery.min.js', 'page': u'http://remote.cyanlabs.net/htpc/couchpotato/'}

**Comment by bakman2** [comment]
it can't find the ID. Will either remove the "active" or think of another solution.

**Comment by bakman2** [comment]
> Thumbnail item titles in Plex, Kodi, CouchPotato etc need to be either smaller or lighter as with certain titles it can push the final thumbnail beyond the content margin so it moves to next row and leaves a gap.

I don't see this happening ? (in plex on iphone)

**Comment by Hellowlol** [comment]
That is related to https://github.com/Hellowlol/HTPC-Manager/issues/302#issuecomment-128278558.

**Comment by thatbritguy** [comment]
I can't access Plex on iPhone due to the menu button issue, but it happens when viewing on a computer.

**Comment by bakman2** [comment]
Yes the menu icon is a problem, working on it.

**Comment by fma965** [comment]
if we have the nav active working wouldn't this theme look better with 
`.page-header {
    display: none;
}`

EDIT: this would break the upload/download speed counters in deluge and other torrent/downloaders though so lets ignore this :)

**Comment by thatbritguy** [comment]
Also all the header buttons would be inaccessible :P

**Comment by bakman2** [comment]
it is unfortunate that the pulldown menu lives in the h1 tag, makes it a bit more difficult to customize.

```
h1.page-header.page-title>a{display:none;}
```

would work, but if there is no indicator it would hide the black bar (and if there is a menu it would "float")

**Comment by bakman2** [comment]
Is it possible to move the inline css of the refresh icons to the theme css ? (currently hardcoded in dash.js)

**Comment by fma965** [comment]
isn't it also bad code to have the menu insde a h1 tag?

**Comment by Hellowlol** [comment]
@Fma965 I think it was done to simply alignment. I have no idea about best pratice for that. I dont care aslong as it works :D

@bakman2 Yes, we can just use the ids and or classes that are added, just remember that you have to do it for them all...

**Comment by fma965** [comment]
yeah i care to some extent but some of it is just too annoying to sort :)

**Comment by Hellowlol** [comment]
Hehe, i know the feeling. HTPC-Manager has been a collective effort and clear when reading the code. There is alot of different way to do stuff :D

**Comment by bakman2** [comment]
@raysguy see #306 most should be fixed (i have recreated the theme)

**Comment by Hellowlol** [comment]
This is the modal from sickrage if you search for something
![image](https://cloud.githubusercontent.com/assets/1214134/9119778/d9daae74-3c78-11e5-8eef-0befb1d3fab3.png)

Progressbar text needs to a bit lower because of the line height.
![image](https://cloud.githubusercontent.com/assets/1214134/9119835/2869b0e4-3c79-11e5-8479-a56a6ac88178.png)

**Comment by Hellowlol** [comment]
@bakman2 the bugs I mentioned was not fixed when you redid your skin.

**Comment by bakman2** [comment]
The modal looks the same in the onyx theme ?
the bar should look like this:
![screen shot 2015-08-09 at 08 28 17](https://cloud.githubusercontent.com/assets/333960/9153804/a5456876-3e70-11e5-9de5-2035cdc383da.jpg)

**Comment by Hellowlol** [comment]
I hadn't check that, but a lot of the dark themes has issues with modals. Especially modules that rays guy does not use.

**Comment by Hellowlol** [comment]
Closing this as i assume the issues was fixed when the theme was updated.
